version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/slapshot # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:8.14-browsers # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: install-packages
          command: yarn install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
    test:
      - run: # run tests
          name: test
          command: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
